### ISSUE TITLE
Homebrew cask

### ISSUE THREAD

**Issue by smileytechguy** [arnoappenzeller/PiPifier#20]
Hi,

I would like to create a homebrew cask (caskroom.io) for this awesome tool, but would need a precompiled .safariext or similar.

**Comment by derimagia** [comment]
Agreed, I don't like installing macstore apps and generally avoid it.

**Comment by arnoappenzeller** [comment]
Not sure if this is useful for a broad audience. Whats the advantage over compiling it by yourself from the repo?

**Comment by derimagia** [comment]
I'd say they aren't comparable. Cask doesn't generally compile apps at all. It's also more simple than the mac store, and compiling an app is more complicated than the app store so it's a bit on the other end of the spectrum.

Cask isn't as much like brew in terms of brew can compile the apps. Cask is pretty much like a package manager for your GUI apps. Look at the terminal here: https://github.com/caskroom/homebrew-cask  - it doesn't do too much when installing an app.

It's easy to implement a cask for it and most of the time if it uses sparkle-like appcasts it will update it automatically in the repo. As a user you can manage your apps using this, install new ones and keep a list of your installed apps. The fact that you can export all your software to a file and install it on any other mac is extremely useful.

**Comment by Saklad5** [comment]
The most important part of Homebrew-Cask is that it makes it extremely easy to manage, update, and uninstall programs. It doesn’t have an official `upgrade` command quite yet, but numerous people have contributed tools that let you do it.
