### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by DanielO** [arnoappenzeller/PiPifier#28]
This (very useful :) extension seems to cause Safari Web Content processes to leak memory (rather badly). For example after a day or so I find some of those processes using 4 to 15 (!) GB of memory.

This doesn't seem related to actually using the extension but it's hard to be sure since Safari Web Content processes are shared between web pages :-/

**Comment by smileytechguy** [comment]
If you would look in the hidden Debug menu of Safari, it may be able to shed some light on what is going on.  Enable this menu item with the following terminal command:
```shell
defaults write com.apple.Safari IncludeInternalDebugMenu 1
```

**Comment by arnoappenzeller** [comment]
Hmm I cannot see the same behaviour when running PiPifier. Do you have an example page where this is happening?

**Comment by DanielO** [comment]
It happens most frequently with https://app.asana.com but that is a paid service, so..
I do see it on twitter.com sometimes but not right now.

This one is agrab after it was running over night ![4 14gb](https://cloud.githubusercontent.com/assets/643662/22171035/27338f7c-dfd6-11e6-9974-50e91eb842b9.png)

And this one just after I killed it and it reloaded ![312mb](https://cloud.githubusercontent.com/assets/643662/22171034/234dd8ae-dfd6-11e6-865b-2a36d7f4d6a6.png)

The overnight was was reporting it was using 4.14GB of memory in activity monitor, after reload 312MB.

**Comment by smileytechguy** [comment]
Definitely a leak, with all that `bmalloc` usage...I don't know how to fix this, but im sure there is a way to

**Comment by DanielO** [comment]
I updated to the git version and can no longer repro this so I'm closing it.
