### ISSUE TITLE
Safari Tech Preview

### ISSUE THREAD

**Issue by kfcain** [arnoappenzeller/PiPifier#33]
Could just be me, but PiPifier seems to have been broken with the release of Safari Tech Preview 29. It worked with v28 and previous versions, but after updating today, it seems it no longer works for any type of HTML5 videos I try, including Netflix. 

thanks

**Comment by KZeni** [comment]
It seems this might be related to https://github.com/arnoappenzeller/PiPifier/issues/37 as this is an issue with Safari TP as well as the standard version of Safari.

**Comment by arnoappenzeller** [comment]
Closing this as a duplicate from #37
