### ISSUE TITLE
Submit the extension to Apple

### ISSUE THREAD

**Issue by LouisCAD** [arnoappenzeller/PiPifier#5]
Hi, you should submit your extension [here](https://developer.apple.com/safari/extensions/submission/) to get more users and make updates and installation a one click operation.

**Comment by arnoappenzeller** [comment]
I agree and I will add this to one of Apple's official distribution channels soon

**Comment by pranayshirolkar** [comment]
I think that LouisCAD believes in the extension, and I do too. Submit it to Apple and get more users and trust!

**Comment by arnoappenzeller** [comment]
Thank you all for your feedback. 

It's now on the mac appstore:
https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1160374471&mt=12

It also has a little buy me a cup of tea button if you want to support me!

Tell all your friends :-)
