### ISSUE TITLE
Include a LICENSE in the repository

### ISSUE THREAD

**Issue by deviantintegral** [arnoappenzeller/PiPifier#55]
It would be great if you could include a license, so if others ever contribute in the future they know what terms their code will be distributed under.

**Comment by Clete2** [comment]
Please add a license so I can download it at my organization.

**Comment by Clete2** [comment]
@arnoappenzeller Would you be able to do this? Easy fix and would allow more people to use your app.

**Comment by arnoappenzeller** [comment]
Here is a license now.

PS: Sorry for my inactivity. Side project time has become very constrained (And shame on me - that was such a ridiculous small action to do :) )
