### ISSUE TITLE
Bitcoin mining malware detected in PiPifier.app

### ISSUE THREAD

**Issue by pieterdd** [arnoappenzeller/PiPifier#56]
So this just happened on my machine…

![malware popup](https://user-images.githubusercontent.com/1407980/36499477-ad917086-1741-11e8-84ab-1bfbd290c558.png)

Avast matched a file in PiPifier.app with MacOS:BitCoinMiner-AS [Trj]. What's going on here?

**Comment by arnoappenzeller** [comment]
I'm not sure from which source you got PiPifier but in the Mac AppStore Version and here the Github Version (where you can see the source - the only Versions I provide) is no Bitcoin miner.
In addition avast points to libswiftDispatch.dylib which is part of the Swift programming language standard library.
I would rather see this as a false positive

**Comment by arnoappenzeller** [comment]
No worries - I guess there are a lot of extension that are doing nasty things like mining or affiliate hijacking...
So thanks for the report!

What version of Avast are you using? If I have some spare time I'll check it out and maybe get in touch with them and find out what's causing this

**Comment by jesperstig** [comment]
It's not hijacked by another process.

The exact same just happened to me. It must be a false positive by Avast

**Comment by arnoappenzeller** [comment]
Wow... this is becoming scary. 

I just contacted Avast about this - I hope they fix it soon. 
Not looking forward to the AppStore reviews and mails from people thinking the app is mining Bitcoin...

**Comment by arnoappenzeller** [comment]
Seems PiPifier is not the only one affected:
* [1Password](https://discussions.agilebits.com/discussion/86860/avg-quarantined-1password-libswiftdispatch-dylib)
* [Xcode](https://twitter.com/rheckart/status/966420689438863365)

**Comment by arnoappenzeller** [comment]
This is a confirmed false positive (see (here)[https://forum.avast.com/index.php?topic=216164.0])

Should be fixed by Avast soon
