### ISSUE TITLE
Netflix subtitle in original window

### ISSUE THREAD

**Issue by OutOfBedlam** [arnoappenzeller/PiPifier#6]
It works fine with Netflix movie, but the only problems is that subtitle stays on the original window.
I don't know if it is possible to make subtitle to move on the pip window

**Comment by arnoappenzeller** [comment]
This would rather be a feature request for Apple to add subtitle capability to PiP or making Netflix to add the subtitle inside the video.
With the current API it's just not achievable.

**Comment by emilstahl** [comment]
@arnoappenzeller
> This would rather be a feature request for Apple to add subtitle capability to PiP

I don't think so 😁 

 HTML 5 subtitle
![screen shot 2016-10-27 at 18 03 01](https://cloud.githubusercontent.com/assets/3885790/19775162/cef285f6-9c6f-11e6-82b2-9cc747140319.png)

PiP![screen shot 2016-10-27 at 18 03 01](https://cloud.githubusercontent.com/assets/3885790/19775161/ceedea8c-9c6f-11e6-9bba-d6f4a4f3eb15.png)

**Comment by arnoappenzeller** [comment]
Yeah but Netflix customly lays the subtitle over the video and only the video can go in PiP. So no chance yet

**Comment by zomars** [comment]
Maybe leaving the [link to Apple feedback](https://www.apple.com/feedback/safari.html) would be useful here.

**Comment by mariusaee** [comment]
Hi!
Is there any news about YouTube subs in pip?
