### ISSUE TITLE
Update icon for macOS Big Sur?

### ISSUE THREAD

**Issue by ghost** [arnoappenzeller/PiPifier#76]
Suggestion to update the icon to match the new macOS Big Sur icon style?
Proposed new icon: https://raw.githubusercontent.com/elrumo/macOS_Big_Sur_icons_replacements/master/icons/Pipifier.icns

**Comment by arnoappenzeller** [comment]
Hey I really like that icon.

I just updated some stuff for Big Sur and iOS 14 but didn't use that icon yet.
Will definitely think about in the future.

PS: Sorry for my inactivity. Side project time has become very constrained

**Comment by arnoappenzeller** [comment]
Big Sur Icon is now here
