### ISSUE TITLE
Can’t download on iPhone on iOS 14

### ISSUE THREAD

**Issue by ericbf** [arnoappenzeller/PiPifier#77]
According to the docs, this should be downloadable on iPhone on iOS 14. It does not seem to be the case:

![42BE2C3C-177D-42B0-AC43-F0A4C4FD42EF](https://user-images.githubusercontent.com/2483476/91383774-f6ff7b00-e7fa-11ea-8567-e23435e63e51.png)

**Comment by arnoappenzeller** [comment]
It will be available in the App Store when iOS 14 is released
