### ISSUE TITLE
m1 build

### ISSUE THREAD

**Issue by psande** [arnoappenzeller/PiPifier#81]
Hi!

Any plans on making a release to upgrade the extension universal binaries?

Thanks for your work! I use your extension everyday!

**Comment by cschildhorn** [comment]
Would be great.

**Comment by chinmaythosar** [comment]
This would be really awesome.

**Comment by arnoappenzeller** [comment]
A M1 build is now available.
Sorry for the long wait!

**Comment by psande** [comment]
Thanks @arnoappenzeller !
