### ISSUE TITLE
Uninstallation method for Safari extension 

### ISSUE THREAD

**Issue by arnoappenzeller** [arnoappenzeller/PiPifier#9]
It seems like there is no native possibility to remove the plugin from Safari. 

Needs to be investigated.

**Comment by kabiroberai** [comment]
It actually is possible, you just have to do Product -> Clean (⇧⌘K) in Xcode and then reopen Safari.

**Comment by arnoappenzeller** [comment]
I found out that there is one routine to get the plugin to disappear from Safari's menu:
1. Deactivate the extension in Safari
2. Now go to Launchpad (Press F4) and hold the mouse on PiPifier. Then delete it by pressing the X-Button.
